# Análise de Desempenho do Palmeiras no Campeonato Brasileiro 2026 (Em andamento)

## 1. Definição do Problema de Negócio

### 1.1. Contexto

O Campeonato Brasileiro de Futebol é uma das ligas mais competitivas do mundo, e o desempenho de um clube ao longo da temporada é de grande interesse para torcedores, analistas esportivos e a própria gestão do time. A capacidade de analisar dados de partidas pode revelar padrões, pontos fortes e fracos, e auxiliar na tomada de decisões estratégicas.

Este projeto foca na análise do desempenho do Sociedade Esportiva Palmeiras no Campeonato Brasileiro de 2026, utilizando dados públicos de resultados de jogos. O objetivo é transformar esses dados brutos em *insights* claros sobre a performance do time.

### 1.2. Problema de Negócio

Para torcedores e a comissão técnica, entender o desempenho de um time vai além de apenas ver a tabela de classificação. Questões como:

- **Desempenho Geral:** Qual foi o balanço de vitórias, empates e derrotas do Palmeiras?
- **Performance em Casa vs. Fora:** O time joga melhor em casa ou como visitante? Há uma diferença significativa na pontuação ou no saldo de gols?
- **Eficiência Ofensiva e Defensiva:** Quantos gols o time marcou e sofreu? Qual a média de gols por partida?
- **Consistência ao Longo do Tempo:** Existem períodos (meses ou dias da semana) em que o desempenho é notavelmente melhor ou pior?

Responder a essas perguntas de forma estruturada e visual é fundamental para avaliar a campanha do time e identificar áreas para melhoria.

### 1.3. Objetivos do Projeto

O objetivo principal deste projeto é realizar uma Análise Exploratória de Dados (EDA) do desempenho do Palmeiras no Campeonato Brasileiro de 2026 para extrair *insights* relevantes.

Os objetivos específicos são:

- **Calcular Métricas de Desempenho:** Determinar o número total de vitórias, empates, derrotas e pontos conquistados pelo Palmeiras.
- **Analisar Gols:** Calcular o total de gols marcados (pró) e sofridos (contra), e o saldo de gols.
- **Comparar Local de Jogo:** Avaliar o desempenho do time em partidas jogadas em casa e fora de casa.
- **Identificar Tendências Temporais:** Analisar a performance do time por mês e por dia da semana para identificar padrões.
- **Identificar Vítimas e Carrascos:** Determinar quais times o Palmeiras mais venceu e mais perdeu.

### 1.4. Critérios de Sucesso

O projeto será considerado um sucesso ao entregar:

- Um *dataset* pré-processado com as informações de desempenho do Palmeiras.
- Métricas claras e concisas sobre o desempenho geral do time.
- Visualizações que comparem o desempenho em casa e fora, e ao longo do tempo.
- Identificação dos principais adversários (vítimas e carrascos).
- Conclusões baseadas em dados que respondam às perguntas de negócio iniciais.
- Dados prontos para importação em ferramentas de BI como o Power BI.

## 2. Importando Bibliotecas

In [ ]:
import pandas as pd
import numpy as np

## 3. Carregando e Compreendendo os Dados

In [ ]:
# Define nome do arquivo
nome_arquivo_csv = 'brasileirao_2026.csv'

In [ ]:
# Carrega o dataset
df_brasileirao_2026 = pd.read_csv(nome_arquivo_csv)

### 3.1. Análise Estrutural do Dataset
Verificação das dimensões, primeiras e últimas linhas, tipos de dados e valores ausentes para uma compreensão inicial do dataset.

In [ ]:
# shape
df_brasileirao_2026.shape

(380, 7)

In [ ]:
# Primeiras linhas
df_brasileirao_2026.head()

,data,rodada,mandante,visitante,gols_mandante,gols_visitante,status
0,2026-01-28T22:00:00Z,1,CA Mineiro,SE Palmeiras,2.0,2.0,FINISHED
1,2026-01-28T22:00:00Z,1,Coritiba FBC,RB Bragantino,0.0,1.0,FINISHED
2,2026-01-28T22:00:00Z,1,SC Internacional,CA Paranaense,0.0,1.0,FINISHED
3,2026-01-28T22:00:00Z,1,EC Vitória,Clube do Remo,2.0,0.0,FINISHED
4,2026-01-28T22:30:00Z,1,Fluminense FC,Grêmio FBPA,2.0,1.0,FINISHED

In [ ]:
# Amostra dos dados
df_brasileirao_2026.sample(10)

,data,rodada,mandante,visitante,gols_mandante,gols_visitante,status
205,2026-07-29T22:30:00Z,21,Mirassol FC,Clube do Remo,NaN,NaN,TIMED
284,2026-10-07T00:00:00Z,29,Fluminense FC,Coritiba FBC,NaN,NaN,SCHEDULED
150,2026-05-16T22:00:00Z,16,Fluminense FC,São Paulo FC,2.0,1.0,FINISHED
201,2026-07-29T20:00:00Z,21,Botafogo FR,Grêmio FBPA,NaN,NaN,TIMED
103,2026-04-12T14:00:00Z,11,CA Paranaense,Chapecoense AF,2.0,0.0,FINISHED
180,2026-07-17T23:00:00Z,19,Fluminense FC,RB Bragantino,NaN,NaN,TIMED
173,2026-05-31T14:00:00Z,18,RB Bragantino,SC Internacional,3.0,1.0,FINISHED
85,2026-04-02T22:00:00Z,9,Santos FC,Clube do Remo,2.0,0.0,FINISHED
349,2026-11-18T00:00:00Z,35,EC Vitória,RB Bragantino,NaN,NaN,SCHEDULED
255,2026-09-05T00:00:00Z,26,Fluminense FC,CR Vasco da Gama,NaN,NaN,SCHEDULED

In [ ]:
# Ultimas linhas
df_brasileirao_2026.tail()

,data,rodada,mandante,visitante,gols_mandante,gols_visitante,status
375,2026-12-02T00:00:00Z,38,Grêmio FBPA,Mirassol FC,NaN,NaN,SCHEDULED
376,2026-12-02T00:00:00Z,38,SE Palmeiras,Coritiba FBC,NaN,NaN,SCHEDULED
377,2026-12-02T00:00:00Z,38,Clube do Remo,SC Corinthians Paulista,NaN,NaN,SCHEDULED
378,2026-12-02T00:00:00Z,38,Santos FC,Botafogo FR,NaN,NaN,SCHEDULED
379,2026-12-02T00:00:00Z,38,CR Vasco da Gama,EC Vitória,NaN,NaN,SCHEDULED

In [ ]:
df_brasileirao_2026.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 380 entries, 0 to 379
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   data            380 non-null    object
 1   rodada          380 non-null    int64
 2   mandante        380 non-null    object
 3   visitante       380 non-null    object
 4   gols_mandante   177 non-null    float64
 5   gols_visitante  177 non-null    float64
 6   status          380 non-null    object
dtypes: float64(2), int64(1), object(4)
memory usage: 20.9+ KB

In [ ]:
print("\nVerificando valores ausentes:\n")
print(df_brasileirao_2026.isnull().sum())

Verificando valores ausentes:

data                0
rodada              0
mandante            0
visitante           0
gols_mandante     203
gols_visitante    203
status              0
dtype: int64

## 4. Pré-processamento e Engenharia de Atributos

### 4.1. Conversão de Tipos e Extração de Informações Temporais
A coluna `data` será convertida para o tipo datetime para permitir a extração de informações como mês e dia da semana, que podem ser úteis para identificar padrões.

In [ ]:
# Convertendo coluna 'data' para datetime
df_brasileirao_2026['data']= pd.to_datetime(df_brasileirao_2026['data'])

In [ ]:
# Criar a condição booleana para verificar a existencia de jogos não finalizados
condicao_nao_finalizados = df_brasileirao_2026['status'] != "FINISHED"
print(f"Quantidade de jogos não finalizados: {condicao_nao_finalizados.sum()} ")

Quantidade de jogos não finalizados: 203

In [ ]:
# Filtras só as partidas finalizadas
df_brasileirao_2026 = df_brasileirao_2026[df_brasileirao_2026['status'] == "FINISHED"]
print(df_brasileirao_2026['status'].value_counts())

status
FINISHED    177
Name: count, dtype: int64

In [ ]:
# Difinir nome do time a ser trabalhado

time = 'SE Palmeiras'

# Criar condição

condicao_palmeiras = (
    (df_brasileirao_2026['mandante'] == time) |
    (df_brasileirao_2026['visitante'] == time)
    )

# Filtrar dados da SE Palmeiras e criar uma copia do DataFrame

df_palmeiras = df_brasileirao_2026[condicao_palmeiras].copy()

# Mostrando primeiras linhas do DataFrame
df_palmeiras.head()

,data,rodada,mandante,visitante,gols_mandante,gols_visitante,status
0,2026-01-28 22:00:00+00:00,1,CA Mineiro,SE Palmeiras,2.0,2.0,FINISHED
15,2026-02-05 00:30:00+00:00,2,SE Palmeiras,EC Vitória,5.0,1.0,FINISHED
28,2026-02-13 00:30:00+00:00,3,SC Internacional,SE Palmeiras,1.0,3.0,FINISHED
36,2026-02-26 00:30:00+00:00,4,SE Palmeiras,Fluminense FC,2.0,1.0,FINISHED
44,2026-03-12 22:30:00+00:00,5,CR Vasco da Gama,SE Palmeiras,2.0,1.0,FINISHED

In [ ]:
df_palmeiras["temporada"] = 2026

### 4.2. Identificação do Local do Jogo e Resultados
Criação de colunas para identificar se o jogo foi em casa ou fora, e para determinar o resultado da partida (Vitória, Empate, Derrota) do ponto de vista do Palmeiras.

In [ ]:
# Criar coluna 'local_jogo'
df_palmeiras['local_jogo'] = df_palmeiras['mandante'].apply(lambda x: 'Casa' if x == 'SE Palmeiras' else 'Fora')

# Validação

print("Total de jogos:", df_palmeiras.shape[0])
print(df_palmeiras['local_jogo'].value_counts())

Total de jogos: 18
local_jogo
Fora    9
Casa    9
Name: count, dtype: int64

In [ ]:
df_palmeiras.head()

,data,rodada,mandante,visitante,gols_mandante,gols_visitante,status,temporada,local_jogo
0,2026-01-28 22:00:00+00:00,1,CA Mineiro,SE Palmeiras,2.0,2.0,FINISHED,2026,Fora
15,2026-02-05 00:30:00+00:00,2,SE Palmeiras,EC Vitória,5.0,1.0,FINISHED,2026,Casa
28,2026-02-13 00:30:00+00:00,3,SC Internacional,SE Palmeiras,1.0,3.0,FINISHED,2026,Fora
36,2026-02-26 00:30:00+00:00,4,SE Palmeiras,Fluminense FC,2.0,1.0,FINISHED,2026,Casa
44,2026-03-12 22:30:00+00:00,5,CR Vasco da Gama,SE Palmeiras,2.0,1.0,FINISHED,2026,Fora

### 4.3. Cálculo de Gols e Pontos
Cálculo dos gols marcados e sofridos pelo Palmeiras em cada partida, e a pontuação obtida (3 para vitória, 1 para empate, 0 para derrota).

In [ ]:
# Gols Pró e Gols Contra Ajustados
# Criar coluna 'gols_pro'
df_palmeiras['gols_pro'] = np.where(df_palmeiras['local_jogo'] == 'Casa', df_palmeiras['gols_mandante'], df_palmeiras['gols_visitante'])

# Criar coluna 'gols_contra'
df_palmeiras['gols_contra'] = np.where(df_palmeiras['local_jogo'] == 'Fora', df_palmeiras['gols_mandante'], df_palmeiras['gols_visitante'])

In [ ]:
# Criando coluna para resultado final do jogo
conditions = [
    df_palmeiras['gols_pro'] > df_palmeiras['gols_contra'],
    df_palmeiras['gols_pro'] == df_palmeiras['gols_contra']
]
choices = ["Vitoria", "Empate"]
df_palmeiras['resultado'] = np.select(conditions, choices, default="Derrota")

In [ ]:
# Criando coluna para pontos conquistados por partida
condicoes = [
    df_palmeiras['resultado'] == 'Vitoria',
    df_palmeiras['resultado'] == 'Empate'
]
pontuacao =  [3, 1]
df_palmeiras['pontos'] = np.select(condicoes, pontuacao, default = 0)

In [ ]:
# Criando coluna de saldo de gols

df_palmeiras ['saldo_de_gols'] = df_palmeiras['gols_pro'] - df_palmeiras['gols_contra']

## 5. Análise Exploratória de Dados (EDA)

### 5.1. Visão Geral do Desempenho do Palmeiras
Primeiras linhas do dataset filtrado e estatísticas descritivas para o Palmeiras.

In [ ]:
df_palmeiras.head()

,data,rodada,mandante,visitante,gols_mandante,gols_visitante,status,temporada,local_jogo,gols_pro,gols_contra,resultado,pontos,saldo_de_gols
0,2026-01-28 22:00:00+00:00,1,CA Mineiro,SE Palmeiras,2.0,2.0,FINISHED,2026,Fora,2.0,2.0,Empate,1,0.0
15,2026-02-05 00:30:00+00:00,2,SE Palmeiras,EC Vitória,5.0,1.0,FINISHED,2026,Casa,5.0,1.0,Vitoria,3,4.0
28,2026-02-13 00:30:00+00:00,3,SC Internacional,SE Palmeiras,1.0,3.0,FINISHED,2026,Fora,3.0,1.0,Vitoria,3,2.0
36,2026-02-26 00:30:00+00:00,4,SE Palmeiras,Fluminense FC,2.0,1.0,FINISHED,2026,Casa,2.0,1.0,Vitoria,3,1.0
44,2026-03-12 22:30:00+00:00,5,CR Vasco da Gama,SE Palmeiras,2.0,1.0,FINISHED,2026,Fora,1.0,2.0,Derrota,0,-1.0

In [ ]:
df_palmeiras.tail()

,data,rodada,mandante,visitante,gols_mandante,gols_visitante,status,temporada,local_jogo,gols_pro,gols_contra,resultado,pontos,saldo_de_gols
129,2026-05-02 21:30:00+00:00,14,SE Palmeiras,Santos FC,1.0,1.0,FINISHED,2026,Casa,1.0,1.0,Empate,1,0.0
142,2026-05-10 20:40:00+00:00,15,Clube do Remo,SE Palmeiras,1.0,1.0,FINISHED,2026,Fora,1.0,1.0,Empate,1,0.0
151,2026-05-17 00:00:00+00:00,16,SE Palmeiras,Cruzeiro EC,1.0,1.0,FINISHED,2026,Casa,1.0,1.0,Empate,1,0.0
162,2026-05-24 00:00:00+00:00,17,CR Flamengo,SE Palmeiras,0.0,3.0,FINISHED,2026,Fora,3.0,0.0,Vitoria,3,3.0
174,2026-05-31 19:00:00+00:00,18,SE Palmeiras,Chapecoense AF,1.0,0.0,FINISHED,2026,Casa,1.0,0.0,Vitoria,3,1.0

In [ ]:
df_palmeiras.sample(10)

,data,rodada,mandante,visitante,gols_mandante,gols_visitante,status,temporada,local_jogo,gols_pro,gols_contra,resultado,pontos,saldo_de_gols
15,2026-02-05 00:30:00+00:00,2,SE Palmeiras,EC Vitória,5.0,1.0,FINISHED,2026,Casa,5.0,1.0,Vitoria,3,4.0
58,2026-03-18 22:00:00+00:00,7,SE Palmeiras,Botafogo FR,2.0,1.0,FINISHED,2026,Casa,2.0,1.0,Vitoria,3,1.0
0,2026-01-28 22:00:00+00:00,1,CA Mineiro,SE Palmeiras,2.0,2.0,FINISHED,2026,Fora,2.0,2.0,Empate,1,0.0
69,2026-03-22 00:00:00+00:00,8,São Paulo FC,SE Palmeiras,0.0,1.0,FINISHED,2026,Fora,1.0,0.0,Vitoria,3,1.0
53,2026-03-15 21:30:00+00:00,6,SE Palmeiras,Mirassol FC,1.0,0.0,FINISHED,2026,Casa,1.0,0.0,Vitoria,3,1.0
174,2026-05-31 19:00:00+00:00,18,SE Palmeiras,Chapecoense AF,1.0,0.0,FINISHED,2026,Casa,1.0,0.0,Vitoria,3,1.0
162,2026-05-24 00:00:00+00:00,17,CR Flamengo,SE Palmeiras,0.0,3.0,FINISHED,2026,Fora,3.0,0.0,Vitoria,3,3.0
44,2026-03-12 22:30:00+00:00,5,CR Vasco da Gama,SE Palmeiras,2.0,1.0,FINISHED,2026,Fora,1.0,2.0,Derrota,0,-1.0
36,2026-02-26 00:30:00+00:00,4,SE Palmeiras,Fluminense FC,2.0,1.0,FINISHED,2026,Casa,2.0,1.0,Vitoria,3,1.0
116,2026-04-19 21:30:00+00:00,12,SE Palmeiras,CA Paranaense,1.0,0.0,FINISHED,2026,Casa,1.0,0.0,Vitoria,3,1.0

### 5.2. Análise de Resultados (Vitórias, Empates, Derrotas)
Contagem e visualização dos resultados das partidas do Palmeiras.

In [ ]:
# Totais Gerais
total_vitorias = df_palmeiras['resultado'].value_counts().get('Vitoria', 0)
total_empates = df_palmeiras['resultado'].value_counts().get('Empate', 0)
total_derrotas = df_palmeiras['resultado'].value_counts().get('Derrota', 0)
total_pontos = df_palmeiras['pontos'].sum()
total_gols_pro = df_palmeiras['gols_pro'].sum()
total_gols_contra = df_palmeiras['gols_contra'].sum()
saldo_de_gol = total_gols_pro - total_gols_contra

print(f"Total de Vitórias: {total_vitorias}")
print(f"Total de Empates: {total_empates}")
print(f"Total de Derrotas: {total_derrotas}")
print(f"Total de Pontos: {total_pontos}")
print(f"Total de Gols a Favor: {total_gols_pro}")
print(f"Total de Gols Contra: {total_gols_contra}")
print(f"Saldo de Gols: {saldo_de_gol}")

Total de Vitórias: 12
Total de Empates: 5
Total de Derrotas: 1
Total de Pontos: 41
Total de Gols a Favor: 30.0
Total de Gols Contra: 13.0
Saldo de Gols: 17.0

In [ ]:
# Calculo de numero de jogos ou numero de rodadas no campeonato
numero_jogos = df_palmeiras.shape[0]

# Calculo de pontos maximos que um time pode fazer
pontos_maximos = numero_jogos * 3

# Calculo de pontos perdidos pelo o palmeiras
pontos_perdidos = pontos_maximos - total_pontos

# Imprime os resultados
print(f"Número de rodadas: {numero_jogos}")
print(f"Total de pontos máximos possiveis no campeonato: {pontos_maximos}")
print(f"Total de pontos conquistados pelo Palmeiras no Campeonato Brasileiro de 2026 até aqui: {total_pontos}")
print(f"Pontos perdidos pelo Palmeiras no Campeonato Brasileiro de 2026 até aqui: {pontos_perdidos}")

Número de rodadas: 18
Total de pontos máximos possiveis no campeonato: 54
Total de pontos conquistados pelo Palmeiras no Campeonato Brasileiro de 2026 até aqui: 41
Pontos perdidos pelo Palmeiras no Campeonato Brasileiro de 2026 até aqui: 13

### 5.3. Desempenho em Casa vs. Fora
Comparação da performance do Palmeiras quando joga como mandante e como visitante.

In [ ]:
# Desempenho Casa x Fora
resumo_casa_fora = (
    df_palmeiras
        .groupby('local_jogo')
        .agg(
            pontos_total=('pontos', 'sum'),
            gols_pro_total=('gols_pro', 'sum'),
            gols_contra_total=('gols_contra', 'sum'),
            vitorias=('resultado', lambda x: (x == 'Vitoria').sum()),
            empates=('resultado', lambda x: (x == 'Empate').sum()),
            derrotas=('resultado', lambda x: (x == 'Derrota').sum())
        )
        .reset_index()
)

resumo_casa_fora

,local_jogo,pontos_total,gols_pro_total,gols_contra_total,vitorias,empates,derrotas
0,Casa,23,16.0,6.0,7,2,0
1,Fora,18,14.0,7.0,5,3,1

In [ ]:
# Métricas percentuais

# Aproveitamento de pontos
aproveitamento_percentual = total_pontos / pontos_maximos * 100

# Média de gols feitos
media_gols_pro = total_gols_pro / numero_jogos

# Média gols contra
media_gols_contra = total_gols_contra / numero_jogos

print(f"Percentual de pontos conquistados: {aproveitamento_percentual:.2f}%")
print(f"Média de gols feitos por jogo: {media_gols_pro:.2f}")
print(f"Média de gols sofridos por jogo: {media_gols_contra:.2f}")

Percentual de pontos conquistados: 75.93%
Média de gols feitos por jogo: 1.67
Média de gols sofridos por jogo: 0.72

## 6. Análise de Vítimas e Carrascos

### 6.1. Maiores Vítimas do Palmeiras
Identificação dos times que o Palmeiras mais venceu no Campeonato Brasileiro de 2025.

In [ ]:
# Identificando as vítimas (times que o Palmeiras mais venceu)
vitorias_mandante = df_palmeiras[(df_palmeiras['mandante'] == time) & (df_palmeiras['resultado'] == 'Vitoria')]['visitante'].value_counts()
vitorias_visitante = df_palmeiras[(df_palmeiras['visitante'] == time) & (df_palmeiras['resultado'] == 'Vitoria')]['mandante'].value_counts()

maiores_vitimas = (vitorias_mandante.add(vitorias_visitante, fill_value=0)).sort_values(ascending=False)
print("Maiores Vítimas do Palmeiras:")
print(maiores_vitimas.head())

Maiores Vítimas do Palmeiras:
Botafogo FR       1.0
CA Paranaense     1.0
CR Flamengo       1.0
Chapecoense AF    1.0
EC Bahia          1.0
Name: count, dtype: float64

### 6.2. Maiores Carrascos do Palmeiras
Identificação dos times que mais venceram o Palmeiras no Campeonato Brasileiro de 2025.

In [ ]:
# Identificando os carrascos (times que mais venceram o Palmeiras)
derrotas_mandante = df_palmeiras[(df_palmeiras['mandante'] == time) & (df_palmeiras['resultado'] == 'Derrota')]['visitante'].value_counts()
derrotas_visitante = df_palmeiras[(df_palmeiras['visitante'] == time) & (df_palmeiras['resultado'] == 'Derrota')]['mandante'].value_counts()

maiores_carrascos = (derrotas_mandante.add(derrotas_visitante, fill_value=0)).sort_values(ascending=False)
print("""
Maiores Carrascos do Palmeiras:
""")
print(maiores_carrascos.head())

Maiores Carrascos do Palmeiras:

mandante
CR Vasco da Gama    1.0
Name: count, dtype: float64

## 7. Preparação para Power BI

Para facilitar a criação de visualizações interativas no Power BI, o DataFrame `df_palmeiras` será exportado para um arquivo CSV. Este arquivo conterá todas as colunas processadas e as métricas de desempenho do Palmeiras, prontas para serem carregadas na ferramenta de BI.

### 7.1. Refinamento dos dados para exportação

In [ ]:
# Ordenação por data

df_palmeiras = df_palmeiras.sort_values('data')

In [ ]:
# Resetar índice

df_palmeiras.reset_index(drop=True, inplace=True)

In [ ]:
df_palmeiras.head(10)

,data,rodada,mandante,visitante,gols_mandante,gols_visitante,status,temporada,local_jogo,gols_pro,gols_contra,resultado,pontos,saldo_de_gols
0,2026-01-28 22:00:00+00:00,1,CA Mineiro,SE Palmeiras,2.0,2.0,FINISHED,2026,Fora,2.0,2.0,Empate,1,0.0
1,2026-02-05 00:30:00+00:00,2,SE Palmeiras,EC Vitória,5.0,1.0,FINISHED,2026,Casa,5.0,1.0,Vitoria,3,4.0
2,2026-02-13 00:30:00+00:00,3,SC Internacional,SE Palmeiras,1.0,3.0,FINISHED,2026,Fora,3.0,1.0,Vitoria,3,2.0
3,2026-02-26 00:30:00+00:00,4,SE Palmeiras,Fluminense FC,2.0,1.0,FINISHED,2026,Casa,2.0,1.0,Vitoria,3,1.0
4,2026-03-12 22:30:00+00:00,5,CR Vasco da Gama,SE Palmeiras,2.0,1.0,FINISHED,2026,Fora,1.0,2.0,Derrota,0,-1.0
5,2026-03-15 21:30:00+00:00,6,SE Palmeiras,Mirassol FC,1.0,0.0,FINISHED,2026,Casa,1.0,0.0,Vitoria,3,1.0
6,2026-03-18 22:00:00+00:00,7,SE Palmeiras,Botafogo FR,2.0,1.0,FINISHED,2026,Casa,2.0,1.0,Vitoria,3,1.0
7,2026-03-22 00:00:00+00:00,8,São Paulo FC,SE Palmeiras,0.0,1.0,FINISHED,2026,Fora,1.0,0.0,Vitoria,3,1.0
8,2026-04-03 00:30:00+00:00,9,SE Palmeiras,Grêmio FBPA,2.0,1.0,FINISHED,2026,Casa,2.0,1.0,Vitoria,3,1.0
9,2026-04-05 22:30:00+00:00,10,EC Bahia,SE Palmeiras,1.0,2.0,FINISHED,2026,Fora,2.0,1.0,Vitoria,3,1.0

### 7.2. Exportação do DataFrame

In [ ]:
# Exportar o DataFrame processado para CSV
df_palmeiras.to_csv("palmeiras_jogos_2026.csv", index=False)

resumo_casa_fora.to_csv("palmeiras_casa_fora_2026.csv", index=False)